# Generated by Django 5.2.7 on 2026-06-21 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('preferred_time_slots', models.JSONField(default=list)),
                ('days_required', models.JSONField(default=list)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
                ('services_needed', models.ManyToManyField(related_name='resident_profiles', to='userdetails.service')),
            ],
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('previous_work_reference', models.CharField(blank=True, max_length=255)),
                ('work_preference', models.CharField(blank=True, max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=50)),
                ('areas_willing_to_work_in', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to=settings.AUTH_USER_MODEL)),
                ('languages_spoken', models.ManyToManyField(related_name='helper_profiles', to='userdetails.language')),
                ('services_offered', models.ManyToManyField(related_name='helper_profiles', to='userdetails.service')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card')], max_length=20)),
                ('file', models.FileField(upload_to='identity_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'doc_type')},
            },
        ),
    ]
