# Generated by Django 5.2.7 on 2026-07-11 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('govt_id_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License')], max_length=20)),
                ('govt_id_number', models.CharField(blank=True, max_length=50)),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='helper_docs/aadhaar/%Y/%m/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='helper_docs/pan/%Y/%m/')),
                ('house_no', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='helper_photos/%Y/%m/')),
                ('police_verification_cert', models.FileField(blank=True, null=True, upload_to='helper_docs/police/%Y/%m/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='helper_docs/address_proof/%Y/%m/')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('working_days', models.JSONField(default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to=settings.AUTH_USER_MODEL)),
                ('languages_spoken', models.ManyToManyField(related_name='helper_profiles', to='userdetails.language')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='resident_photos/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelperServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='userdetails.helperprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_prices', to='userdetails.service')),
            ],
            options={
                'unique_together': {('helper', 'service')},
            },
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='services_offered',
            field=models.ManyToManyField(related_name='helper_profiles', through='userdetails.HelperServicePrice', to='userdetails.service'),
        ),
    ]
