# Generated by Django 5.2.7 on 2026-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='emergency_contact_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='emergency_contact_verified',
            field=models.BooleanField(default=False),
        ),
    ]
