# Generated by Django 5.2.7 on 2026-07-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helperprofile',
            old_name='areas_willing_to_work_in',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='helperprofile',
            old_name='work_preference',
            new_name='emergency_contact_relation',
        ),
        migrations.RenameField(
            model_name='helperprofile',
            old_name='working_hours',
            new_name='govt_id_number',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='previous_work_reference',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='days_required',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='preferred_time_slots',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='services_needed',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='work_type',
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/aadhaar/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/address_proof/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='city',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='full_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='govt_id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License')], max_length=20),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='house_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/pan/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='police_verification_cert',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/police/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='helper_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='working_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resident_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HelperServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='userdetails.helperprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_prices', to='userdetails.service')),
            ],
            options={
                'unique_together': {('helper', 'service')},
            },
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='services_offered',
            field=models.ManyToManyField(related_name='helper_profiles', through='userdetails.HelperServicePrice', to='userdetails.service'),
        ),
        migrations.DeleteModel(
            name='IdentityDocument',
        ),
    ]
