# Generated by Django 5.2.7 on 2026-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_helperprofile_emergency_contact_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='adhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
