# Generated by Django 5.2.7 on 2026-07-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_helperprofile_adhaar_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='avg_rating',
            field=models.FloatField(default=0, max_length=2),
        ),
    ]
