# Generated by Django 5.2.7 on 2026-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_helperprofile_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperprofile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, max_length=2),
        ),
    ]
