# Generated by Django 5.2.7 on 2026-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_alter_helperprofile_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0, max_length=5),
        ),
    ]
