# Generated by Django 5.2.7 on 2026-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_helperprofile_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperprofile',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
