# Generated by Django 5.2.7 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_rename_adhaar_verified_helperprofile_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='area',
            field=models.CharField(default='Vaishali', max_length=100),
            preserve_default=False,
        ),
    ]
