# Generated by Django 5.2.7 on 2026-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0009_helperprofile_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='police_verified',
            field=models.BooleanField(default=False),
        ),
    ]
