# Generated by Django 5.2.7 on 2026-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('maid', 'Maid'), ('customer', 'Customer')], default='customer', max_length=20, verbose_name='Role'),
        ),
    ]
