# Generated by Django 5.2.7 on 2026-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('helper', 'Helper'), ('resident', 'Resident')], default='resident', max_length=20, verbose_name='Role'),
        ),
    ]
